service: blog-nextjs-app

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    NODE_ENV: production

package:
  patterns:
    - '.next/**'
    - 'public/**'
    - '!node_modules/**'

functions:
  app:
    handler: .next/standalone/server.js
    layers:
      - ${cf:layer-arn}
    events:
      - httpApi: '*'

layers:
  nodeModules:
    path: node_modules
    name: ${self:service}-node-modules
    description: Node modules for Next.js app
    compatibleRuntimes:
      - nodejs16.x

plugins:
  - serverless-nextjs-plugin
  - serverless-layers